openapi: 3.0.3
info:
  title: API REST de Integración - Cuenca Travel
  version: "1.0.0"
servers:
  - url: http://localhost:3001/api
paths:
  /integracion/servicios:
    get:
      summary: Buscar servicios (paquetes) con filtros simples
      parameters:
        - in: query
          name: minPrecio
          schema: { type: number }
        - in: query
          name: maxPrecio
          schema: { type: number }
      responses:
        "200": { description: ok }
  /integracion/servicios/{id}:
    get:
      summary: Obtener detalle de un servicio por código
      parameters:
        - in: path
          name: id
          required: true
          schema: { type: string }
      responses:
        "200": { description: ok }
        "404": { description: no encontrado }
  /integracion/disponibilidad:
    get:
      summary: Verificar disponibilidad por sku y fecha (inicio)
      parameters:
        - in: query
          name: sku
          required: true
          schema: { type: string }
        - in: query
          name: inicio
          required: true
          schema: { type: string, format: date }
        - in: query
          name: unidades
          schema: { type: integer }
      responses:
        "200": { description: ok }
  /integracion/cotizar:
    post:
      summary: Cotizar lista de items
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                items:
                  type: array
                  items:
                    type: object
                    properties:
                      codigo: { type: string }
                      adultos: { type: integer }
                      ninos: { type: integer }
      responses:
        "200": { description: ok }
  /integracion/prereservas:
    post:
      summary: Crear una pre-reserva simple (demo)
      responses: { "201": { description: creada } }
  /integracion/confirmar:
    post:
      summary: Confirmar una reserva usando un item
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                item:
                  type: object
                  properties:
                    codigo: { type: string }
                    fecha:  { type: string, format: date }
                    adultos:{ type: integer }
                    ninos:  { type: integer }
      responses:
        "201": { description: creada }
  /integracion/cancelar:
    post:
      summary: Cancelar una reserva por bookingId
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                bookingId: { type: string }
      responses:
        "200": { description: ok }
